-- MySQL Script generated by MySQL Workbench
-- Thu Jun  5 14:27:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MoodRoom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MoodRoom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MoodRoom` DEFAULT CHARACTER SET utf8 ;
USE `MoodRoom` ;

-- -----------------------------------------------------
-- Table `MoodRoom`.`Mood Kits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoodRoom`.`Mood Kits` ;

CREATE TABLE IF NOT EXISTS `MoodRoom`.`Mood Kits` (
  `KitID` VARCHAR(32) NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(450) NULL,
  `MoodTag` VARCHAR(45) NULL,
  `Price` INT NULL,
  `DigitalOnly` TINYINT NULL,
  PRIMARY KEY (`KitID`));


-- -----------------------------------------------------
-- Table `MoodRoom`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoodRoom`.`Orders` ;

CREATE TABLE IF NOT EXISTS `MoodRoom`.`Orders` (
  `OrderID` INT NOT NULL,
  `UserID` VARCHAR(45) NULL,
  `KitID` VARCHAR(32) NOT NULL,
  `OrderDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`OrderID`),
  INDEX `KitID_idx` (`KitID` ASC) VISIBLE,
  INDEX `UserID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `MoodRoom`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `KitID`
    FOREIGN KEY (`KitID`)
    REFERENCES `MoodRoom`.`Mood Kits` (`KitID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `MoodRoom`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MoodRoom`.`Users` ;

CREATE TABLE IF NOT EXISTS `MoodRoom`.`Users` (
  `UserID` VARCHAR(45) NOT NULL,
  `UserName` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(50) NULL,
  `Password` VARCHAR(32) NOT NULL,
  `DateJoined` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`UserID`)
  );


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
